version: '2'
services:
  2uassessment-app:
    image: 2uassessment
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://2uassessment-postgresql:5432/2uAssessment
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  2uassessment-postgresql:
    extends:
      file: postgresql.yml
      service: 2uassessment-postgresql
